<?php
class Handler1 extends abstractHandler{

    public function handler($request)
    {
        if ($request <= 1) {
            echo "Handle Successful";
        } else {
            echo "Handler 1 can not handle this problems, pls handle that!";
            echo "<br>";
            parent::handler($request); // TODO: Change the autogenerated stub
        }
    }


}