<?php
class Hanlder2 extends abstractHandler{
    public function handler($request)
    {
        if ($request<=2) {
            echo "Handle Successful";
        }else{
            echo "Handler 2 can not handle this problems, pls handle that!";
            echo "<br>";
            parent::handler($request); // TODO: Change the autogenerated stub
        }

    }
}