<?php
class TeamLeader extends EmployeeDecorator{
    public function __construct(EmployeeComponent $employee)
    {
        parent::__construct($employee);
    }

    public function doTask()
    {
        return parent::doTask(); // TODO: Change the autogenerated stub
    }

    public function join()
    {
        return parent::join(); // TODO: Change the autogenerated stub
    }

    public function terminate()
    {
        return parent::terminate(); // TODO: Change the autogenerated stub
    }

    public function planning(){
        return "This is planning";
    }

    public function motivate(){
        return "This is motivate";
    }

    public function monitor(){
        return "This is monitor";
    }
}