<?php
class TeamMember extends EmployeeDecorator{
    public function __construct(EmployeeComponent $employee)
    {
        parent::__construct($employee);
    }

    public function doTask()
    {
        return parent::doTask(); // TODO: Change the autogenerated stub
    }

    public function join()
    {
        return parent::join(); // TODO: Change the autogenerated stub
    }

    public function terminate()
    {
        return parent::terminate(); // TODO: Change the autogenerated stub
    }

    public function performTask(){
        return "This is performTask";
    }

    public function coordinateWithOther(){
        return "This is coordinateWithOder";
    }
}