<?php
class TayNguyenFactoryAPhanBon2 extends TayNguyenFactoryAPhanBon {
    public function __construct(GiongCayTrongFactory $factory)
    {
        parent::__construct($factory);
    }

    public function chonGiong(Giong $giong)
    {
        return parent::chonGiong($giong); // TODO: Change the autogenerated stub
    }

    public function addPhanBon()
    {
        return parent::addPhanBon(); // TODO: Change the autogenerated stub
    }

    public function addPhanBon2(){
        return "Them phan bon cho Tieuuu";
    }


}