<?php
class TayNguyenFactoryAPhanBon extends DecoratorFactory{
    public function __construct(GiongCayTrongFactory $factory)
    {
        parent::__construct($factory);
    }

    public function chonGiong(Giong $giong)
    {
        return parent::chonGiong($giong); // TODO: Change the autogenerated stub
    }

    public function addPhanBon()
    {
        return "Them phan bon cho Ca phe";
    }
}